### ISSUE TITLE
Owership?

### ISSUE THREAD

**Issue by rodrigocfd** [DianaNites/Windows#1]
Hi,

I'm the author of [WinLamb C++11 Win32 library](https://github.com/rodrigocfd/winlamb), and I'm currently working on a porting to Rust. I'd like to use the [Windows crate](https://crates.io/crates/windows) if possible, so here's the issue kindly asking for the ownership.

Thank you.

**Comment by DianaNites** [comment]
Apologies, crate has been transferred to Microsoft.
