### ISSUE TITLE
Microsoft ownership

### ISSUE THREAD

**Issue by kennykerr** [DianaNites/Windows#2]
Hi Diana,

I work on the Windows team at Microsoft. I’m responsible for making the Windows platform accessible to Rust developers. So far we’ve contributed crates like [com](https://crates.io/crates/com) and [winrt](https://crates.io/crates/winrt), but would like to provide a far more comprehensive crate that exposes all Windows APIs to Rust developers and would love to use the [windows](https://crates.io/crates/windows) crate to make this possible. 

Please let me know if you have any questions. 

kenny.kerr@microsoft.com

K

**Comment by DianaNites** [comment]
No problem here, happy to make the crate available to Microsoft, especially since `Windows APIs to Rust developers` was my original goal with this before. Till I saw the true scope of it all..

Where should I transfer crate ownership to?

**Comment by kennykerr** [comment]
Thanks Diana, much appreciated. Please add [kennykerr](https://crates.io/users/kennykerr) as an owner and I'll take it from there.

**Comment by DianaNites** [comment]
Done!

**Comment by kennykerr** [comment]
Thanks so much!
